### ISSUE TITLE
Messaging Protocol implementation

### ISSUE THREAD

**Issue by larteyoh** [larteyoh/testshop#105]
```
Details
```

I need to decide on which messaging protocol/binary serialization I will be using for communication between nodes in a decentralized peer-to-peer network.
__The possible candidates include__:
- KRPC Protocol (bencoding) - protocol used by the Kademlia distributed hash table (DHT) to allow nodes in the network to communicate with each other and exchange data. KRPC allows nodes to send and receive messages containing method calls and their parameters, much like other RPC protocols such as XML-RPC or JSON-RPC. However, unlike those protocols, KRPC uses a binary message format that is optimized for efficiency and compactness.
- [x]  MessagePack - like JSON but more lightweight and faster
- Google's protocol buffers (protobuf) - a language-agnostic binary serialization format used for data exchange between applications. It is designed to be a fast, efficient, and extensible way of serializing structured data. Protocol Buffers are widely used in distributed systems because they can be efficiently serialized and deserialized across multiple languages and platforms. Libp2p's use of Protocol Buffers allows for interoperability with other systems that use the same serialization format.
- Wire protocol - for a general-purpose messaging protocol that provides end-to-end encryption and other security features, then the Wire protocol may be a better choice. It is also more simpler to use and understand than Levin. Unfortunately, wire is proprietary.
- Levin protocol - for use in a cryptocurrency network, then the Levin protocol may be more appropriate.

```
References
```
https://github.com/monero-project/monero/blob/master/docs/LEVIN_PROTOCOL.md
https://github.com/sanderfoobar/py-levin

**Comment by ZeusMoose21** [comment]
Check out [SimpleX](https://simplex.chat/), it might have what you are looking for. It's even better than Wire and is open source.
