### ISSUE TITLE
Add basic or advanced search engine

### ISSUE THREAD

**Issue by larteyoh** [larteyoh/testshop#13]
```
Details
```
The search engine should be able to search for sellers by their display name or id, including products either by their name or UPC code and even search for products that fall within a specific category. All of this information can be retrieved from the sqlite3 database.

**When a user searches the name or id of a seller, it will display the seller's profile along with their product listings**

**SQLite, with its full-text search features and whatnot should be sufficient for this task. There's no need to use another external library for this task.**

```
References
```
- https://www.sqlite.org/fts5.html
- initializeDatabase() @ https://github.com/larteyoh/testshop/blob/main/src/gui/backend.cpp (line 53?)

- For viewing all content inside the database, you will need the DB Browser for SQLite which can be downloaded from this link (https://sqlitebrowser.org/dl/)

This should give you a full look on how the database is structured and designed.

```
Bounty reward
```
$0

**Comment by EagleNye** [comment]
Is there a place to view the database structure? There's a lot of queries(including tons commented out and referencing postgres) scattered throughout the codebase that give an idea of the structure, but actual table definitions would be helpful.

**Comment by larteyoh** [comment]
Yeah, I was playing around with the postgresql c library at one point but I've removed it from the project and switched to sqlite3 instead. Take a look at src/gui/backend.cpp @ line 53. Here's a link (https://github.com/larteyoh/testshop/blob/main/src/gui/backend.cpp#L53)

In the file, you should find an "initializeDatabase()" function that initializes the database by creating all the tables and columns. I will probably make some changes to it later (like changing renaming table "products" to "listings" since services can also be sold aside from physical goods). The database scheme design is not final but it should give you an idea of how I want it to look like.
------- Original Message -------

**Comment by larteyoh** [comment]
Oops ... meant to say I will change table "inventory" to "listings"
------- Original Message -------

**Comment by larteyoh** [comment]
Closed as completed. 

Basic search mechanism using SQLite's FTS5 has been implemented and can work on certain search criterias such as `product names`, `product categories`, sale `location` (country), as well as `seller ids`.
