### ISSUE TITLE
Port neroshop client (core and gui) to web using Emscripten/WebAssembly

### ISSUE THREAD

**Issue by larteyoh** [larteyoh/testshop#14]
```
Details
```
To reach a wider audience, it may be necessary to have a light client for neroshop aside from the desktop application.

```
References
```

```
Bounty reward 
```
$0

**Comment by preland** [comment]
I may be interested in helping.

**Comment by preland** [comment]
Sorry for the late response - I had something come up last minute that took some time to deal with. I’m okay with discussing it here.

In terms of what you want exactly, do you just need the source code of these modules to be ported into wasm? What ideally do you want the end result to look like?

**Comment by larteyoh** [comment]
I think I'll need the source code of the external dependencies and the project core and gui source code to be ported to wasm if that is required to run the application on a browser. I'd like to be able to run the Qt/QML based app on the browser as well — this is the end result I'm expecting. I'm not too familiar with Emcripten or WASM, but I can probably give you some references that may help if you decide that you're up for the task.

**Comment by preland** [comment]
Some references would be helpful. I think I’ll be able to work on this, although I’m not sure how long it’ll take exactly, especially considering the size of the dependencies (I am also assuming that they will need to be ported via Emscripten).

**Comment by larteyoh** [comment]
I don't mind if it takes a lot time. And I definitely agree with you in that the number of dependencies is quite a lot 😄. Majority of them are built from source into static libraries as shown in "external/CMakeLists.txt".

Also, I've talked to the main developer of monero-cpp, woodser and he gave me this information regarding how he is able to port his project (hope it helps):

"monero-javascript builds monero-cpp and monero-project defined in monero-javascript/CMakeLists.txt, and the build scripts in monero-javascript/bin handle building ./dist assets for web"

"... one approach could be to fork monero-javascript and modify for your web project

but ideally you're using the released versions of the libraries"

"yes, you could fork monero-javascript to inherit the structure of building c++ to wasm and then modify with your files, or start a new project to build c++ to wasm with emscripten similar to monero-javascript. either way, the js would point down to your c++, which is built against monero-cpp (which could be a submodule, for example). just thinking how to bootstrap a new web project, but maybe there is a better way"

**Comment by preland** [comment]
That is interesting. I'm not entirely sure if using a js port of the monero dependencies would play nice with wasm, although it is an interesting thought.

I have already cloned the repo and have begun building it. However, I have noticed that there are issues with building the dependencies (It currently hangs on 'make release-static' trying to build src/rpc/CMakeFiles/obj_rpc.dir/core_rpc_server.cpp.o). I suspect that this is because I am developing the project on Arch, which you noted has an outdated dependency list in the README. I am probably just missing a dependency, as the Arch install is very fresh. If you could help me in updating the dependency list, that would be appreciated.

**Comment by larteyoh** [comment]
I figured that building monero would be the biggest obstacle that you'd face. The Arch dependencies list for monero is actually complete (I only used what I needed for the static monero libs). It's only missing the Qt/QML dependencies. I'll switch my distro from Ubuntu to Arch so that I can try to build it there (It's been a while since I've used Arch).
This is the link to the [complete dependency list for monero](https://github.com/monero-project/monero#dependencies) just in case (Look for the "Install all dependencies at once on Arch" section when you scroll down).

**Comment by preland** [comment]
I had a look at that and downloaded the missing dependencies. It didn’t fix the issue, but I noticed that the dependencies that are manually installed in the README instructions (expat and unbound) have packages that could be installed via package managers. Is there a reason for manually compiling those dependencies?

On a similar note, would the most current version of monero-cpp be viable for this project? If so, I think I may try building the static libraries for that version and see if I can build the project with those dependencies instead.

**Comment by larteyoh** [comment]
The instructions for manually installing and building expat and unbound were taken from [here](https://github.com/monero-ecosystem/monero-cpp#using-this-library-in-your-project). Before Monero version 0.18, that was not required. You could just simply use the system's version of libunbound at the time and Monero was a lot more easier to build than it is now. I don't know the reason why they changed it.

**Comment by preland** [comment]
I see, I was not aware that there was an issue like that in the newer versions of monero-cpp. I will try to see if i can get any version of the newer dependencies to build. If that doesn't work, I'll probably have to do a more in-depth analysis of the script that keeps hanging the process; i am still hopeful that this isn't caused by an arbitrary race condition.

**Comment by larteyoh** [comment]
monero-cpp is actually a wrapper library for [monero-project](https://github.com/monero-project/monero). I forgot to mention that there is a [pull request](https://github.com/monero-project/monero/pull/8564) that tackles the issue with monero static builds. This is for Ubuntu (not sure If the same applies to Arch).

**Comment by larteyoh** [comment]
Also thank you for your efforts. I know this isn't easy but I have faith in you. I'll try to help as much as I can if possible.

**Comment by larteyoh** [comment]
I managed to get monero-project to build on Manjaro (which is based on Arch) somehow. I didn't get the same error as you did except I did get an "undefined reference to icu_*" error I was able to fix by adding `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -licuio -licui18n -licuuc -licudata")` to "external/monero-cpp/external/monero-project/CMakeLists.txt"
